gcp:
  project: stablecoin-fds
  gcs:
    raw_bucket: stablecoin-fds-raw
    processed_bucket: stablecoin-fds-processed
  bigquery:
    dataset: stablecoin_fds
providers:
  ethereum:
    etherscan_api_key: 
